"""create_initial_tables

Revision ID: 685f9ff7188e
Revises: 3a0537953a82
Create Date: 2026-05-28 21:18:18.592097

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "685f9ff7188e"
down_revision: Union[str, Sequence[str], None] = "3a0537953a82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
